# Generated by Django 3.2 on 2023-10-02 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Неверное имя пользователя. Допускаются только буквы, цифры и знак подчеркивания. Не может содержать символы «@», «.», «+» или «-».', regex='^[\\w]+[^@\\.\\+\\-]*$')]),
        ),
    ]
